version: '3.8'

services:
  microservicio2:
    image: microservicio2:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker