version: '3.8'

services:
  microservicio2:
    image: microservicio2:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
        - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P4ssword!
      MYSQL_DATABASE: my-app