version: '3.8'

services:
  microservicio2:
    image: microservicio2:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest